---
abstract: 'Improve an assembly by scaffolding, contig ordering and gap closing.'
author:
  - 'Andrew J. Page <ap13@sanger.ac.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio_AssemblyImprovement
resources:
  homepage: http://www.sanger.ac.uk/
  repository: https://github.com/sanger-pathogens/assembly_improvement.git
version: 1.140300
